###
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "xxx",
  "email": "xxx@xxx.com",
  "password": "xxx123"
}

###
GET http://localhost:3000/users

###
GET http://localhost:3000/users/xxx

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "xxx@xxx.com",
  "password": "xxx123"
}